[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=0
upload_speed = 115200
lib_deps = 
  yknivag/ESP_OTA_GitHub
  bblanchon/ArduinoJson@^6.21.0
  paulstoffregen/Time@^1.6.1